# create and claim a persistent volume for our pod
# this works because we enabled cloud-provider=aws
# so it can create a disk for itself

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
#    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/aws-ebs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
# deploy the mysql container

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      # deploying MySQL from the default Docker Hub image
      containers:
      - image: mysql
        name: mysql
        resources:
          requests:
            cpu: 1
            memory: 2Gi
        env:
          # The mysql image will configure a root password with the value of MYSQL_ROOT_PASSWORD...
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-credentials
                key: rootpw
          # ... an initial non-root user with a username of the value of MYSQL_USER ...
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: mysql-credentials
                key: user
          # ... and a password of the value of MYSQL_PASSWORD ...
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-credentials
                key: password
          # ... and an initial database named with the value of MYSQL_DATABASE (while granting MYSQL_USER superuser access.)
          - name: MYSQL_DATABASE
            value: sakila
        livenessProbe:
          tcpSocket:
            port: 3306
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: /var/lib/mysql
          subPath: data
          name: database
      volumes:
      - name: database
        configMap:
        persistentVolumeClaim:
          claimName: database

---
# expose this on mysql.default.svc.cluster.local to the cluster
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: ClusterIP
  ports:
  - port: 3306
    protocol: TCP
  selector:
    app: mysql
